version: '3'

services:
  server:
    build: 
      context: ./packages/back
      dockerfile: DockerFile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
    command: npm start
  
  client:
    build:
      context: ./packages/front
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
      - SKIP_PREFLIGHT_CHECK=true
    command: npm start
      
    